# Generated by MCP Server Generator
FROM python:3.11-slim

WORKDIR /usr/src/app

# --- Server Configuration ---
# Options: web, stdio
ENV TRANSPORT_MODE="web"
ENV HOST="0.0.0.0"
ENV PORT="8000"

# --- Credentials & Config ---


ENV MCP_CONFIG='{"operations": {"get_enriched_order_details": {"path": "/orders/{order_id}/details", "method": "get", "source_config": {"type": "http", "steps": [{"step_id": "fetch_order", "method": "get", "url": "http://host.docker.internal:8001/orders/${path_params.order_id}"}, {"step_id": "get_product_details", "method": "get", "url": "http://host.docker.internal:8001/products/${fetch_order.product_id}"}]}, "auth_scheme_name": "InternalApiKeyAuth", "parameters": [{"name": "order_id", "in": "path", "required": true, "schema": {"type": "string"}}]}}, "security_schemes": {"InternalApiKeyAuth": {"type": "apiKey", "in": "header", "name": "X-Internal-API-Key"}}}'

# --- Application Setup ---
# CORRECTED: Copy the entire package directory
COPY ./src/generic_mcp_server/ ./generic_mcp_server/
RUN pip install --no-cache-dir -r ./generic_mcp_server/requirements.txt

EXPOSE ${PORT}

# CORRECTED: Run the app as a module to fix relative imports
CMD ["python", "-u", "-m", "generic_mcp_server.run"]