# Generated by MCP Server Generator
FROM python:3.11-slim

WORKDIR /usr/src/app

# --- Server Configuration ---
# Options: web, stdio
ENV TRANSPORT_MODE="web"
ENV HOST="0.0.0.0"
ENV PORT="8000"

# --- Credentials & Config ---



# Point to the config file instead of inline JSON
ENV MCP_CONFIG_FILE="/usr/src/app/mcp_config.json"

# --- Application Setup ---
# Copy the config file first
COPY mcp_config.json /usr/src/app/mcp_config.json

# Copy the entire package directory
COPY ./src/generic_mcp_server/ ./generic_mcp_server/
RUN pip install --no-cache-dir -r ./generic_mcp_server/requirements.txt

EXPOSE ${PORT}

# Run the app as a module to fix relative imports
CMD ["python", "-u", "-m", "generic_mcp_server.run"]